--
DROP TABLE T520_TITULO_MOV;
DROP TABLE T510_TITULO;
DROP TABLE T500_FORNECEDOR;
DROP TABLE T157_TIPO_DOCUMENTO;
DROP TABLE T145_HISTORICO;
DROP TABLE T001_USUARIO;
--
-- *********************
-- 
-- *********************
CREATE TABLE DBO.T001_USUARIO
(T001_IDUSUARIO   INTEGER     NOT NULL IDENTITY(1,1),
 T001_CANOME      VARCHAR(50) NOT NULL,
 T001_CACPF       VARCHAR(11) NOT NULL,
 T001_CAEMAIL     VARCHAR(50) NULL,
 T001_CASENHA     VARCHAR(20) NOT NULL);

 
ALTER TABLE DBO.T001_USUARIO ADD CONSTRAINT PK_T001_USUARIO PRIMARY KEY CLUSTERED (T001_IDUSUARIO ASC);

-- *********************
-- 
-- *********************
CREATE TABLE DBO.T157_TIPO_DOCUMENTO
(T157_IDTIPDOC  INTEGER     NOT NULL IDENTITY(1,1),
 T001_IDUSUARIO INTEGER     NOT NULL,
 T157_CATIPDOC  CHAR(01)    NOT NULL,
 T157_CANOME    VARCHAR(40) NOT NULL,
 T157_CASIGLA   VARCHAR(10));
--
ALTER TABLE T157_TIPO_DOCUMENTO ADD CONSTRAINT PK_T157_TIPO_DOCUMENTO PRIMARY KEY(T157_IDTIPDOC);
ALTER TABLE T157_TIPO_DOCUMENTO ADD CONSTRAINT FK_T157_TIPO_DOCUMENTO_T001_USUARIO FOREIGN KEY(T001_IDUSUARIO) REFERENCES T001_USUARIO(T001_IDUSUARIO)

-- *********************
-- 
-- *********************
CREATE TABLE DBO.T145_HISTORICO
(T145_IDHISTORICO INTEGER      NOT NULL IDENTITY(1,1),
 T001_IDUSUARIO   INTEGER      NOT NULL,
 T145_CDHISTORICO VARCHAR(04)  NOT NULL,
 T145_CANOME      VARCHAR(40)  NOT NULL,
 T145_CADEBCRE    CHAR(01)     NOT NULL,
 T145_CASUCINTO   VARCHAR(20)  NULL);
--
ALTER TABLE T145_HISTORICO ADD CONSTRAINT PK_T145_HISTORICO PRIMARY KEY(T145_IDHISTORICO);
ALTER TABLE T145_HISTORICO ADD CONSTRAINT FK_T145_HISTORICO_T001_USUARIO FOREIGN KEY(T001_IDUSUARIO) REFERENCES T001_USUARIO(T001_IDUSUARIO)

-- *********************
-- 
-- *********************
CREATE TABLE DBO.T500_FORNECEDOR
(T500_IDFORNECEDOR     INTEGER      NOT NULL IDENTITY(1,1),
 T001_IDUSUARIO        INTEGER      NOT NULL,
 T500_CDFORNECEDOR     INTEGER      NULL,
 T500_CANOME           VARCHAR(60)  NOT NULL,
 T500_DTCADASTRO       DATE         NULL);
--
ALTER TABLE T500_FORNECEDOR ADD CONSTRAINT PK_T500_FORNECEDOR PRIMARY KEY(T500_IDFORNECEDOR);
ALTER TABLE T500_FORNECEDOR ADD CONSTRAINT FK_T500_FORNECEDOR_T001_USUARIO FOREIGN KEY(T001_IDUSUARIO) REFERENCES T001_USUARIO(T001_IDUSUARIO)

-- *********************
-- 
-- *********************
CREATE TABLE DBO.T510_TITULO
(T510_IDTITULO     INTEGER        NOT NULL IDENTITY(1,1),
 T001_IDUSUARIO    INTEGER        NOT NULL,
 T510_NRINTERNO    INTEGER        NULL,
 T510_CANUMERO     VARCHAR(20)    NULL,
 T510_CALETRA      CHAR(01)       NULL,
 T510_DTEMISSAO    DATE           NOT NULL,
 T510_DTVENCTO     DATE           NOT NULL,
 T510_VLNOMINAL    NUMERIC(10,2)  NOT NULL,
 T157_IDTIPDOC     INTEGER        NOT NULL,
 T500_IDFORNECEDOR INTEGER        NOT NULL,
 T157_CDTIPDOC     CHAR(01)       NULL,
 T500_CDFORNECEDOR INTEGER        NULL);
--
ALTER TABLE T510_TITULO ADD CONSTRAINT PK_T510_TITULO PRIMARY KEY(T510_IDTITULO);
ALTER TABLE T510_TITULO ADD CONSTRAINT FK_T510_TITULO_T157_TIPO_DOCUM FOREIGN KEY(T157_IDTIPDOC) REFERENCES T157_TIPO_DOCUMENTO(T157_IDTIPDOC);
ALTER TABLE T510_TITULO ADD CONSTRAINT FK_T510_TITULO_T500_FORNECEDOR FOREIGN KEY(T500_IDFORNECEDOR) REFERENCES T500_FORNECEDOR(T500_IDFORNECEDOR);
ALTER TABLE T510_TITULO ADD CONSTRAINT FK_T510_TITULO_T001_USUARIO FOREIGN KEY(T001_IDUSUARIO) REFERENCES T001_USUARIO(T001_IDUSUARIO)
--ALTER TABLE T510_TITULO ADD CONSTRAINT CK_T510_TITULO_T510_DTEMISSAO CHECK (T510_DTEMISSAO <= T510_DTVENCTO); 

-- *********************
-- 
-- *********************
CREATE TABLE DBO.T520_TITULO_MOV
(T520_IDTITULO_MOV    INTEGER       NOT NULL IDENTITY(1,1),
 T520_DTDIGITA        DATE          NULL,
 T520_DTCONTABIL      DATE          NOT NULL,
 T145_CDHISTORICO     VARCHAR(04)   NULL,
 T520_VLLANCTO        NUMERIC(10,2) NOT NULL,
 T510_IDTITULO        INTEGER       NOT NULL,
 T145_IDHISTORICO     INTEGER       NOT NULL,
 T520_NRINTERNO       INTEGER       NULL,
 T520_CADOCUM         VARCHAR(20)   NULL);
--
ALTER TABLE T520_TITULO_MOV ADD CONSTRAINT PK_T520_TITULO_MOV PRIMARY KEY(T520_IDTITULO_MOV);
--ALTER TABLE T520_TITULO_MOV ADD CONSTRAINT FK_T520_TITULO_MOV_T510_TITULO FOREIGN KEY(T510_IDTITULO) REFERENCES T510_TITULO(T510_IDTITULO);
--ALTER TABLE T520_TITULO_MOV ADD CONSTRAINT FK_T520_TITULO_T145_HISTORICO FOREIGN KEY(T145_IDHISTORICO) REFERENCES T145_HISTORICO(T145_IDHISTORICO);

--